apiVersion: v1
kind: Service
metadata:
  name: vote
  namespace: voting-app
spec:
  type: LoadBalancer   # Use NodePort if Minikube
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: vote
